name: Build standalone app

on:
  push:
    branches:
      - prod-d3
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      EXPO_USERNAME: ${{secrets.EXPO_USERNAME}}
      EXPO_PASSWORD: ${{secrets.EXPO_PASSWORD}}
      EXPO_ANDROID_KEYSTORE_PASSWORD: ${{secrets.ANDROID_STOREPASS}}
      EXPO_ANDROID_KEY_PASSWORD: ${{secrets.ANDROID_KEYPASS}}
    defaults:
      run:
        working-directory: expo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      # avoid global install permission problems
      - name: Change npm prefix
        run: |
          npm config set prefix /tmp/local
          echo "/tmp/local/bin" >> $GITHUB_PATH

      - name: Install and config
        run: |
          npm install -g --unsafe-perm turtle-cli expo-cli
          npm install
          expo login -u ${{secrets.EXPO_USERNAME}} -p ${{secrets.EXPO_PASSWORD}}
          echo "${{secrets.ANDROID_KEYSTORE_ASC}}" | base64 -d > keystore.jks

      - name: Build apk (production)
        run: |
          expo publish --release-channel prod-d3
          turtle build:android -o /tmp/d3.apk -t apk --release-channel prod-d3 --keystore-path keystore.jks --keystore-alias d3

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: d3.apk
          path: /tmp/d3.apk
