name: Heroku Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Main
        if: github.event.pull_request.merged == true && github.ref == 'main'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mycampsite-team12"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "express"